name: Preview [main]

on:
  push:
    branches:
      - main

jobs:
  preview-android:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v2

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: ğŸ— Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ğŸ“¦ Install dependencies
        run: yarn

      - name: ğŸš€ Publish preview
        run: |
          EAS_BUILD_RESULT=$(eas build -p android --profile preview --non-interactive)
          echo "EAS_BUILD_RESULT<<EOF" >> $GITHUB_ENV
          echo "$EAS_BUILD_RESULT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        id: preview_build_android

      - name: ğŸ› ï¸ Extract APK URL
        uses: actions-ecosystem/action-regex-match@v2
        id: regex_match
        with:
          text: ${{ env.EAS_BUILD_RESULT }}
          regex: 'Open this link on your Android devices \(or scan the QR code\) to install the app:[\r\n]+([^\r\n]+)'
          flags: gm

      - name: ğŸ’¬ Comment in Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: 'main ë¸Œëœì¹˜ preview (android)'
          text: "APK ë‹¤ìš´ë¡œë“œ: ${{ steps.regex_match.outputs.group1 }}"
          fields: author, message
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()

  preview-web:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v2

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: ğŸ— Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x

      - name: ğŸ“¦ Install dependencies
        run: yarn

      - name: ğŸ‘· Create production build
        run: expo build:web

      - name: ğŸš€ Publish preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        id: firebase_hosting
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_HOSTING }}"
          expires: 30d
          channelId: preview

      - name: ğŸ’¬ Comment in Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: 'main ë¸Œëœì¹˜ preview (web)'
          text: "ì›¹ì‚¬ì´íŠ¸ URL: ${{ steps.firebase_hosting.outputs.details_url }} (${{ steps.firebase_hosting.outputs.expire_time }} ë§Œë£Œ)"
          fields: author, message
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
